name: expense_planner
description: Personal budget planner

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # HTTP
  dio: ^5.4.3

  # Secure token storage
  flutter_secure_storage: ^9.2.2

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
